version: 1.80.0-{build}
environment:
  global:
    JAVA_HOME: C:\Program Files\Java\jdk1.7.0
    
platform:
  - x86
  - x64
configuration:
  - Debug
  - Release

# branches to build
branches:
  # whitelist
  only:
  - master
  - develop

# Operating system (build VM template)
#os: Windows Server 2012 R2

# clone directory
clone_folder: c:\projects\liblogicalaccess-libnfc

install:
  - ps: |
      Add-Type -AssemblyName System.IO.Compression.FileSystem
      if (!(Test-Path -Path "C:\maven" )) {
        (new-object System.Net.WebClient).DownloadFile(
          'http://www.us.apache.org/dist/maven/maven-3/3.2.5/binaries/apache-maven-3.2.5-bin.zip',
          'C:\maven-bin.zip'
        )
        [System.IO.Compression.ZipFile]::ExtractToDirectory("C:\maven-bin.zip", "C:\maven")
      }
  - cmd: SET PATH=C:\maven\apache-maven-3.2.5\bin;%JAVA_HOME%\bin;%PATH%
  - cmd: SET MAVEN_OPTS=-XX:MaxPermSize=2g -Xmx4g
  - cmd: SET JAVA_OPTS=-XX:MaxPermSize=2g -Xmx4g
  - ps: |
      Add-Type -AssemblyName System.IO.Compression.FileSystem
        (new-object System.Net.WebClient).DownloadFile(
          'http://download.islog.com/mavenSettingsAppVeyor.xml',
          'C:\maven\apache-maven-3.2.5\conf\settings.xml'
        )
        
build:
  project: INSTALL.vcxproj

# scripts to run before build
before_build:
  - cd c:\projects\liblogicalaccess-libnfc
  - mvn -q dependency:copy-dependencies
  - 7z x target/* -opackages
  - ps: |
      if (($env:PLATFORM -eq "x64") -and ($env:CONFIGURATION -eq "Release"))
      { cmake.exe -DCMAKE_BUILD_TYPE=Release -DTARGET_ARCH=x64 -DLIB_SUFFIX=x64/Release -G"Visual Studio 12 Win64" -Tv120_xp . -DCMAKE_INSTALL_PREFIX=./install . }
      elseif (($env:PLATFORM -eq "x64") -and ($env:CONFIGURATION -eq "Debug"))
      { cmake.exe -DCMAKE_BUILD_TYPE=Debug -DTARGET_ARCH=x64 -DLIB_SUFFIX=x64/Debug -G"Visual Studio 12 Win64" -Tv120_xp . -DCMAKE_INSTALL_PREFIX=./install . }
      elseif (($env:PLATFORM -eq "x86") -and ($env:CONFIGURATION -eq "Release"))
      { cmake.exe -DCMAKE_BUILD_TYPE=Release -DTARGET_ARCH=Win32 -DLIB_SUFFIX=Win32/Release -G"Visual Studio 12" -Tv120_xp . -DCMAKE_INSTALL_PREFIX=./install . }
      elseif (($env:PLATFORM -eq "x86") -and ($env:CONFIGURATION -eq "Debug"))
      { cmake.exe -DCMAKE_BUILD_TYPE=Debug -DTARGET_ARCH=Win32 -DLIB_SUFFIX=Win32/Debug -G"Visual Studio 12" -Tv120_xp . -DCMAKE_INSTALL_PREFIX=./install . }
cache:
  - C:\maven\
  - C:\Users\appveyor\.m2
